# Generated by Django 4.1 on 2022-10-12 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_likepost_alter_post_no_of_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='no_of_like',
            new_name='no_of_likes',
        ),
    ]
